/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../../types/enums.js";

/**
 * The base model type of the robot.
 */
export const NewRobotModel = {
  Android: "android",
  Humanoid: "humanoid",
  Rover: "rover",
} as const;
/**
 * The base model type of the robot.
 */
export type NewRobotModel = ClosedEnum<typeof NewRobotModel>;

export type NewRobot = {
  /**
   * The name of the robot.
   */
  name: string;
  /**
   * The base model type of the robot.
   */
  model: NewRobotModel;
};

/** @internal */
export const NewRobotModel$inboundSchema: z.ZodNativeEnum<
  typeof NewRobotModel
> = z.nativeEnum(NewRobotModel);

/** @internal */
export const NewRobotModel$outboundSchema: z.ZodNativeEnum<
  typeof NewRobotModel
> = NewRobotModel$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace NewRobotModel$ {
  /** @deprecated use `NewRobotModel$inboundSchema` instead. */
  export const inboundSchema = NewRobotModel$inboundSchema;
  /** @deprecated use `NewRobotModel$outboundSchema` instead. */
  export const outboundSchema = NewRobotModel$outboundSchema;
}

/** @internal */
export const NewRobot$inboundSchema: z.ZodType<
  NewRobot,
  z.ZodTypeDef,
  unknown
> = z.object({
  name: z.string(),
  model: NewRobotModel$inboundSchema,
});

/** @internal */
export type NewRobot$Outbound = {
  name: string;
  model: string;
};

/** @internal */
export const NewRobot$outboundSchema: z.ZodType<
  NewRobot$Outbound,
  z.ZodTypeDef,
  NewRobot
> = z.object({
  name: z.string(),
  model: NewRobotModel$outboundSchema,
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace NewRobot$ {
  /** @deprecated use `NewRobot$inboundSchema` instead. */
  export const inboundSchema = NewRobot$inboundSchema;
  /** @deprecated use `NewRobot$outboundSchema` instead. */
  export const outboundSchema = NewRobot$outboundSchema;
  /** @deprecated use `NewRobot$Outbound` instead. */
  export type Outbound = NewRobot$Outbound;
}
