/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  Robot,
  Robot$inboundSchema,
  Robot$Outbound,
  Robot$outboundSchema,
} from "./robot.js";

export type RobotList = {
  /**
   * Total number of robots.
   */
  totalItems: number;
  /**
   * Current page number.
   */
  page: number;
  /**
   * Number of robots per page.
   */
  pageSize: number;
  robots: Array<Robot>;
};

/** @internal */
export const RobotList$inboundSchema: z.ZodType<
  RobotList,
  z.ZodTypeDef,
  unknown
> = z.object({
  totalItems: z.number().int(),
  page: z.number().int(),
  pageSize: z.number().int(),
  robots: z.array(Robot$inboundSchema),
});

/** @internal */
export type RobotList$Outbound = {
  totalItems: number;
  page: number;
  pageSize: number;
  robots: Array<Robot$Outbound>;
};

/** @internal */
export const RobotList$outboundSchema: z.ZodType<
  RobotList$Outbound,
  z.ZodTypeDef,
  RobotList
> = z.object({
  totalItems: z.number().int(),
  page: z.number().int(),
  pageSize: z.number().int(),
  robots: z.array(Robot$outboundSchema),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace RobotList$ {
  /** @deprecated use `RobotList$inboundSchema` instead. */
  export const inboundSchema = RobotList$inboundSchema;
  /** @deprecated use `RobotList$outboundSchema` instead. */
  export const outboundSchema = RobotList$outboundSchema;
  /** @deprecated use `RobotList$Outbound` instead. */
  export type Outbound = RobotList$Outbound;
}
