/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { activationActivateRobot } from "../funcs/activationActivateRobot.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as components from "../models/components/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Activation extends ClientSDK {
  /**
   * Activate the robot
   *
   * @remarks
   * Activates the robot after it has been assembled. Once activated, the robot will begin functioning with all configured features and capabilities. This operation changes the robot's status to "active" and records the activation time.
   */
  async activateRobot(
    request: operations.ActivateRobotRequest,
    options?: RequestOptions,
  ): Promise<components.RobotActivation> {
    return unwrapAsync(activationActivateRobot(
      this,
      request,
      options,
    ));
  }
}
