/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { featuresConfigureRobotFeatures } from "../funcs/featuresConfigureRobotFeatures.js";
import { featuresGetRobotFeatures } from "../funcs/featuresGetRobotFeatures.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as components from "../models/components/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Features extends ClientSDK {
  /**
   * Get robot's features
   *
   * @remarks
   * Retrieves the list of features configured for the specified robot.
   */
  async getRobotFeatures(
    request: operations.GetRobotFeaturesRequest,
    options?: RequestOptions,
  ): Promise<components.RobotFeatures> {
    return unwrapAsync(featuresGetRobotFeatures(
      this,
      request,
      options,
    ));
  }

  /**
   * Configure features of the robot
   *
   * @remarks
   * Sets up robot functionalities by adding or updating features for the specified robot.
   */
  async configureRobotFeatures(
    request: operations.ConfigureRobotFeaturesRequest,
    options?: RequestOptions,
  ): Promise<components.RobotFeatures> {
    return unwrapAsync(featuresConfigureRobotFeatures(
      this,
      request,
      options,
    ));
  }
}
