/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { partsAddRobotParts } from "../funcs/partsAddRobotParts.js";
import { partsGetRobotParts } from "../funcs/partsGetRobotParts.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as components from "../models/components/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Parts extends ClientSDK {
  /**
   * Get robot's parts
   *
   * @remarks
   * Retrieves the list of parts associated with the specified robot.
   */
  async getRobotParts(
    request: operations.GetRobotPartsRequest,
    options?: RequestOptions,
  ): Promise<components.RobotParts> {
    return unwrapAsync(partsGetRobotParts(
      this,
      request,
      options,
    ));
  }

  /**
   * Add parts to the robot
   *
   * @remarks
   * Adds parts to the specified robot design. This operation creates new parts or updates existing ones associated with the robot.
   */
  async addRobotParts(
    request: operations.AddRobotPartsRequest,
    options?: RequestOptions,
  ): Promise<components.RobotParts> {
    return unwrapAsync(partsAddRobotParts(
      this,
      request,
      options,
    ));
  }
}
