/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { ClientSDK } from "../lib/sdks.js";
import { Activation } from "./activation.js";
import { Assembly } from "./assembly.js";
import { Features } from "./features.js";
import { Parts } from "./parts.js";
import { Robots } from "./robots.js";

export class BuildaBot extends ClientSDK {
  private _robots?: Robots;
  get robots(): Robots {
    return (this._robots ??= new Robots(this._options));
  }

  private _parts?: Parts;
  get parts(): Parts {
    return (this._parts ??= new Parts(this._options));
  }

  private _features?: Features;
  get features(): Features {
    return (this._features ??= new Features(this._options));
  }

  private _assembly?: Assembly;
  get assembly(): Assembly {
    return (this._assembly ??= new Assembly(this._options));
  }

  private _activation?: Activation;
  get activation(): Activation {
    return (this._activation ??= new Activation(this._options));
  }
}
