/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { expect, test } from "vitest";
import { BuildaBot } from "../index.js";

test("Activation Activate Robot Robot Activated Example", async () => {
  const buildaBot = new BuildaBot({
    apiKeyAuth: process.env["BUILDABOT_API_KEY_AUTH"] ?? "",
  });
  const result = await buildaBot.activation.activateRobot({
    robotId: "f47ac10b-58cc-4372-a567-0e02b2c3d479",
  });
  expect(result).toBeDefined();
  expect(result).toBeDefined();
  expect(result).toEqual({
    robotId: "f47ac10b-58cc-4372-a567-0e02b2c3d479",
    status: "active",
    activationTime: new Date("2023-10-15T12:00:00Z"),
    capabilities: [
      "Voice Recognition",
      "Obstacle Avoidance",
    ],
    links: [
      {
        rel: "self",
        href: "/v1/robots/f47ac10b-58cc-4372-a567-0e02b2c3d479/activate",
      },
    ],
  });
});

test("Activation Activate Robot", async () => {
  const buildaBot = new BuildaBot({
    apiKeyAuth: process.env["BUILDABOT_API_KEY_AUTH"] ?? "",
  });
  const result = await buildaBot.activation.activateRobot({
    robotId: "f47ac10b-58cc-4372-a567-0e02b2c3d479",
  });
  expect(result).toBeDefined();
  expect(result).toBeDefined();
  expect(result).toEqual({
    robotId: "1ab28d86-b67a-4fac-a4b5-5693e5fe4d4a",
    status: "active",
    activationTime: new Date("2023-10-15T12:00:00Z"),
    capabilities: [
      "Voice Recognition",
      "Obstacle Avoidance",
    ],
    links: [
      {
        rel: "self",
        href: "/v1/robots/f47ac10b-58cc-4372-a567-0e02b2c3d479/parts",
      },
    ],
  });
});

test("Activation Activate Robot Bad Request Example", async () => {
  const buildaBot = new BuildaBot({
    apiKeyAuth: process.env["BUILDABOT_API_KEY_AUTH"] ?? "",
  });
  const result = await buildaBot.activation.activateRobot({
    robotId: "f47ac10b-58cc-4372-a567-0e02b2c3d479",
  });
  expect(result).toBeDefined();
});
