/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { expect, test } from "vitest";
import { BuildaBot } from "../index.js";

test("Assembly Assemble Robot Robot Assembled Example", async () => {
  const buildaBot = new BuildaBot({
    apiKeyAuth: process.env["BUILDABOT_API_KEY_AUTH"] ?? "",
  });
  const result = await buildaBot.assembly.assembleRobot({
    robotId: "f47ac10b-58cc-4372-a567-0e02b2c3d479",
  });
  expect(result).toBeDefined();
  expect(result).toBeDefined();
  expect(result).toEqual({
    robotId: "f47ac10b-58cc-4372-a567-0e02b2c3d479",
    name: "T-800",
    model: "android",
    status: "designing",
    links: [
      {
        rel: "self",
        href: "/v1/robots/f47ac10b-58cc-4372-a567-0e02b2c3d479",
      },
      {
        rel: "parts",
        href: "/v1/robots/f47ac10b-58cc-4372-a567-0e02b2c3d479/parts",
      },
      {
        rel: "features",
        href: "/v1/robots/f47ac10b-58cc-4372-a567-0e02b2c3d479/features",
      },
    ],
  });
});

test("Assembly Assemble Robot", async () => {
  const buildaBot = new BuildaBot({
    apiKeyAuth: process.env["BUILDABOT_API_KEY_AUTH"] ?? "",
  });
  const result = await buildaBot.assembly.assembleRobot({
    robotId: "f47ac10b-58cc-4372-a567-0e02b2c3d479",
  });
  expect(result).toBeDefined();
  expect(result).toBeDefined();
  expect(result).toEqual({
    robotId: "b32f64ee-7f0c-42d8-891e-c7c0de554bc9",
    name: "T-800",
    model: "android",
    status: "designing",
    links: [
      {
        rel: "self",
        href: "/v1/robots/f47ac10b-58cc-4372-a567-0e02b2c3d479/parts",
      },
    ],
  });
});

test("Assembly Assemble Robot Bad Request Example", async () => {
  const buildaBot = new BuildaBot({
    apiKeyAuth: process.env["BUILDABOT_API_KEY_AUTH"] ?? "",
  });
  const result = await buildaBot.assembly.assembleRobot({
    robotId: "f47ac10b-58cc-4372-a567-0e02b2c3d479",
  });
  expect(result).toBeDefined();
});
