/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { expect, test } from "vitest";
import { BuildaBot } from "../index.js";

test("Parts Get Robot Parts Robot Parts Example", async () => {
  const buildaBot = new BuildaBot({
    apiKeyAuth: process.env["BUILDABOT_API_KEY_AUTH"] ?? "",
  });
  const result = await buildaBot.parts.getRobotParts({
    robotId: "f47ac10b-58cc-4372-a567-0e02b2c3d479",
  });
  expect(result).toBeDefined();
  expect(result).toBeDefined();
  expect(result).toEqual({
    robotId: "f47ac10b-58cc-4372-a567-0e02b2c3d479",
    parts: [
      {
        partId: "550e8400-e29b-41d4-a716-446655440000",
        type: "arm",
        name: "Hydraulic Arm",
        quantity: 2,
      },
      {
        partId: "550e8400-e29b-41d4-a716-446655440001",
        type: "sensor",
        name: "Infrared Sensor",
        quantity: 1,
      },
    ],
  });
});

test("Parts Get Robot Parts", async () => {
  const buildaBot = new BuildaBot({
    apiKeyAuth: process.env["BUILDABOT_API_KEY_AUTH"] ?? "",
  });
  const result = await buildaBot.parts.getRobotParts({
    robotId: "f47ac10b-58cc-4372-a567-0e02b2c3d479",
  });
  expect(result).toBeDefined();
  expect(result).toBeDefined();
  expect(result).toEqual({
    robotId: "2d1f0530-bdab-4671-9816-bfff3aed07b2",
    parts: [
      {
        partId: "fee81f11-9849-4f3e-8dfd-f49cd98d372c",
        type: "arm",
        name: "Hydraulic Arm",
        quantity: 2,
      },
    ],
  });
});

test("Parts Get Robot Parts Unauthorized Example", async () => {
  const buildaBot = new BuildaBot({
    apiKeyAuth: process.env["BUILDABOT_API_KEY_AUTH"] ?? "",
  });
  const result = await buildaBot.parts.getRobotParts({
    robotId: "f47ac10b-58cc-4372-a567-0e02b2c3d479",
  });
  expect(result).toBeDefined();
});

test("Parts Add Robot Parts Add Parts Example", async () => {
  const buildaBot = new BuildaBot({
    apiKeyAuth: process.env["BUILDABOT_API_KEY_AUTH"] ?? "",
  });
  const result = await buildaBot.parts.addRobotParts({
    robotId: "f47ac10b-58cc-4372-a567-0e02b2c3d479",
    addParts: {
      parts: [
        {
          type: "arm",
          name: "Hydraulic Arm",
          quantity: 2,
        },
        {
          type: "sensor",
          name: "Infrared Sensor",
          quantity: 1,
        },
      ],
    },
  });
  expect(result).toBeDefined();
  expect(result).toBeDefined();
  expect(result).toEqual({
    robotId: "8066b4f2-986e-432d-a062-1ab7d80d332f",
    parts: [
      {
        partId: "615f2029-ed8d-458d-bb69-6dc405a4b653",
        type: "arm",
        name: "Hydraulic Arm",
        quantity: 2,
      },
      {
        partId: "e0d39f90-b914-4fbe-8335-3fc3abbbc47c",
        type: "arm",
        name: "Hydraulic Arm",
        quantity: 2,
      },
    ],
  });
});

test("Parts Add Robot Parts", async () => {
  const buildaBot = new BuildaBot({
    apiKeyAuth: process.env["BUILDABOT_API_KEY_AUTH"] ?? "",
  });
  const result = await buildaBot.parts.addRobotParts({
    robotId: "f47ac10b-58cc-4372-a567-0e02b2c3d479",
    addParts: {
      parts: [
        {
          type: "arm",
          name: "Hydraulic Arm",
          quantity: 2,
        },
        {
          type: "sensor",
          name: "Infrared Sensor",
          quantity: 1,
        },
      ],
    },
  });
  expect(result).toBeDefined();
  expect(result).toBeDefined();
  expect(result).toEqual({
    robotId: "ce496808-866d-4be4-a65d-c2df4017bd27",
    parts: [
      {
        partId: "a0031590-e410-4de6-a0a8-f57db5394523",
        type: "arm",
        name: "Hydraulic Arm",
        quantity: 2,
      },
      {
        partId: "d10d5371-aac5-40f5-94c4-cfe9b908559c",
        type: "arm",
        name: "Hydraulic Arm",
        quantity: 2,
      },
      {
        partId: "3e5e22a6-bf1a-4d24-abc2-01ce981342dc",
        type: "arm",
        name: "Hydraulic Arm",
        quantity: 2,
      },
    ],
  });
});

test("Parts Add Robot Parts Parts Added Example", async () => {
  const buildaBot = new BuildaBot({
    apiKeyAuth: process.env["BUILDABOT_API_KEY_AUTH"] ?? "",
  });
  const result = await buildaBot.parts.addRobotParts({
    robotId: "f47ac10b-58cc-4372-a567-0e02b2c3d479",
    addParts: {
      parts: [
        {
          type: "arm",
          name: "Hydraulic Arm",
          quantity: 2,
        },
        {
          type: "arm",
          name: "Hydraulic Arm",
          quantity: 2,
        },
        {
          type: "arm",
          name: "Hydraulic Arm",
          quantity: 2,
        },
      ],
    },
  });
  expect(result).toBeDefined();
  expect(result).toBeDefined();
  expect(result).toEqual({
    robotId: "f47ac10b-58cc-4372-a567-0e02b2c3d479",
    parts: [
      {
        partId: "550e8400-e29b-41d4-a716-446655440000",
        type: "arm",
        name: "Hydraulic Arm",
        quantity: 2,
      },
      {
        partId: "550e8400-e29b-41d4-a716-446655440001",
        type: "sensor",
        name: "Infrared Sensor",
        quantity: 1,
      },
    ],
  });
});

test("Parts Add Robot Parts Bad Request Example", async () => {
  const buildaBot = new BuildaBot({
    apiKeyAuth: process.env["BUILDABOT_API_KEY_AUTH"] ?? "",
  });
  const result = await buildaBot.parts.addRobotParts({
    robotId: "f47ac10b-58cc-4372-a567-0e02b2c3d479",
    addParts: {
      parts: [
        {
          type: "arm",
          name: "Hydraulic Arm",
          quantity: 2,
        },
        {
          type: "arm",
          name: "Hydraulic Arm",
          quantity: 2,
        },
      ],
    },
  });
  expect(result).toBeDefined();
});
