/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { expect, test } from "vitest";
import { BuildaBot } from "../index.js";

test("Robots List Robots Robot List Example", async () => {
  const buildaBot = new BuildaBot({
    apiKeyAuth: process.env["BUILDABOT_API_KEY_AUTH"] ?? "",
  });
  const result = await buildaBot.robots.listRobots({
    page: 1,
    pageSize: 20,
  });
  expect(result).toBeDefined();
  expect(result).toBeDefined();
  expect(result).toEqual({
    totalItems: 2,
    page: 1,
    pageSize: 20,
    robots: [
      {
        robotId: "f47ac10b-58cc-4372-a567-0e02b2c3d479",
        name: "T-800",
        model: "android",
        status: "designing",
        links: [
          {
            rel: "self",
            href: "/v1/robots/f47ac10b-58cc-4372-a567-0e02b2c3d479",
          },
        ],
      },
      {
        robotId: "a6b9c9b5-4d7c-4a72-b1cb-4b5e4e5e6e0c",
        name: "Mars Rover",
        model: "rover",
        status: "active",
        links: [
          {
            rel: "self",
            href: "/v1/robots/a6b9c9b5-4d7c-4a72-b1cb-4b5e4e5e6e0c",
          },
        ],
      },
    ],
  });
});

test("Robots List Robots", async () => {
  const buildaBot = new BuildaBot({
    apiKeyAuth: process.env["BUILDABOT_API_KEY_AUTH"] ?? "",
  });
  const result = await buildaBot.robots.listRobots({
    page: 1,
    pageSize: 20,
  });
  expect(result).toBeDefined();
  expect(result).toBeDefined();
  expect(result).toEqual({
    totalItems: 100,
    page: 1,
    pageSize: 20,
    robots: [
      {
        robotId: "8b986a7e-f6c8-49e1-910d-cdfc7c1a2f86",
        name: "T-800",
        model: "android",
        status: "designing",
        links: [
          {
            rel: "self",
            href: "/v1/robots/f47ac10b-58cc-4372-a567-0e02b2c3d479/parts",
          },
        ],
      },
    ],
  });
});

test("Robots List Robots Unauthorized Example", async () => {
  const buildaBot = new BuildaBot({
    apiKeyAuth: process.env["BUILDABOT_API_KEY_AUTH"] ?? "",
  });
  const result = await buildaBot.robots.listRobots({
    page: 1,
    pageSize: 20,
  });
  expect(result).toBeDefined();
});

test("Robots Create Robot New Robot Example1", async () => {
  const buildaBot = new BuildaBot({
    apiKeyAuth: process.env["BUILDABOT_API_KEY_AUTH"] ?? "",
  });
  const result = await buildaBot.robots.createRobot({
    name: "T-800",
    model: "android",
  });
  expect(result).toBeDefined();
  expect(result).toBeDefined();
  expect(result).toEqual({
    robotId: "d7e5e6d6-e1d4-417a-9483-1457fbf1493e",
    name: "T-800",
    model: "android",
    status: "designing",
    links: [
      {
        rel: "self",
        href: "/v1/robots/f47ac10b-58cc-4372-a567-0e02b2c3d479/parts",
      },
    ],
  });
});

test("Robots Create Robot New Robot Example2", async () => {
  const buildaBot = new BuildaBot({
    apiKeyAuth: process.env["BUILDABOT_API_KEY_AUTH"] ?? "",
  });
  const result = await buildaBot.robots.createRobot({
    name: "Mars Rover",
    model: "rover",
  });
  expect(result).toBeDefined();
  expect(result).toBeDefined();
  expect(result).toEqual({
    robotId: "60a8aa02-87af-49d2-94a8-034d4390368e",
    name: "T-800",
    model: "android",
    status: "designing",
    links: [
      {
        rel: "self",
        href: "/v1/robots/f47ac10b-58cc-4372-a567-0e02b2c3d479/parts",
      },
      {
        rel: "self",
        href: "/v1/robots/f47ac10b-58cc-4372-a567-0e02b2c3d479/parts",
      },
    ],
  });
});

test("Robots Create Robot Robot Created Example", async () => {
  const buildaBot = new BuildaBot({
    apiKeyAuth: process.env["BUILDABOT_API_KEY_AUTH"] ?? "",
  });
  const result = await buildaBot.robots.createRobot({
    name: "<value>",
    model: "rover",
  });
  expect(result).toBeDefined();
  expect(result).toBeDefined();
  expect(result).toEqual({
    robotId: "f47ac10b-58cc-4372-a567-0e02b2c3d479",
    name: "T-800",
    model: "android",
    status: "designing",
    links: [
      {
        rel: "self",
        href: "/v1/robots/f47ac10b-58cc-4372-a567-0e02b2c3d479",
      },
      {
        rel: "parts",
        href: "/v1/robots/f47ac10b-58cc-4372-a567-0e02b2c3d479/parts",
      },
      {
        rel: "features",
        href: "/v1/robots/f47ac10b-58cc-4372-a567-0e02b2c3d479/features",
      },
    ],
  });
});

test("Robots Create Robot Bad Request Example", async () => {
  const buildaBot = new BuildaBot({
    apiKeyAuth: process.env["BUILDABOT_API_KEY_AUTH"] ?? "",
  });
  const result = await buildaBot.robots.createRobot({
    name: "<value>",
    model: "rover",
  });
  expect(result).toBeDefined();
});

test("Robots Get Robot Robot Example", async () => {
  const buildaBot = new BuildaBot({
    apiKeyAuth: process.env["BUILDABOT_API_KEY_AUTH"] ?? "",
  });
  const result = await buildaBot.robots.getRobot({
    robotId: "f47ac10b-58cc-4372-a567-0e02b2c3d479",
  });
  expect(result).toBeDefined();
  expect(result).toBeDefined();
  expect(result).toEqual({
    robotId: "f47ac10b-58cc-4372-a567-0e02b2c3d479",
    name: "T-800",
    model: "android",
    status: "designing",
    links: [
      {
        rel: "self",
        href: "/v1/robots/f47ac10b-58cc-4372-a567-0e02b2c3d479",
      },
      {
        rel: "parts",
        href: "/v1/robots/f47ac10b-58cc-4372-a567-0e02b2c3d479/parts",
      },
      {
        rel: "features",
        href: "/v1/robots/f47ac10b-58cc-4372-a567-0e02b2c3d479/features",
      },
    ],
  });
});

test("Robots Get Robot", async () => {
  const buildaBot = new BuildaBot({
    apiKeyAuth: process.env["BUILDABOT_API_KEY_AUTH"] ?? "",
  });
  const result = await buildaBot.robots.getRobot({
    robotId: "f47ac10b-58cc-4372-a567-0e02b2c3d479",
  });
  expect(result).toBeDefined();
  expect(result).toBeDefined();
  expect(result).toEqual({
    robotId: "4f3424ca-fffb-4bb3-9b92-9eed7eef46ca",
    name: "T-800",
    model: "android",
    status: "designing",
    links: [
      {
        rel: "self",
        href: "/v1/robots/f47ac10b-58cc-4372-a567-0e02b2c3d479/parts",
      },
      {
        rel: "self",
        href: "/v1/robots/f47ac10b-58cc-4372-a567-0e02b2c3d479/parts",
      },
      {
        rel: "self",
        href: "/v1/robots/f47ac10b-58cc-4372-a567-0e02b2c3d479/parts",
      },
    ],
  });
});

test("Robots Get Robot Unauthorized Example", async () => {
  const buildaBot = new BuildaBot({
    apiKeyAuth: process.env["BUILDABOT_API_KEY_AUTH"] ?? "",
  });
  const result = await buildaBot.robots.getRobot({
    robotId: "f47ac10b-58cc-4372-a567-0e02b2c3d479",
  });
  expect(result).toBeDefined();
});
