/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type ActivateRobotRequest = {
  /**
   * Unique identifier of the robot. This ID is generated upon robot creation and is required for subsequent operations on the robot.
   *
   * @remarks
   */
  robotId: string;
};

/** @internal */
export const ActivateRobotRequest$inboundSchema: z.ZodType<
  ActivateRobotRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  robotId: z.string(),
});

/** @internal */
export type ActivateRobotRequest$Outbound = {
  robotId: string;
};

/** @internal */
export const ActivateRobotRequest$outboundSchema: z.ZodType<
  ActivateRobotRequest$Outbound,
  z.ZodTypeDef,
  ActivateRobotRequest
> = z.object({
  robotId: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ActivateRobotRequest$ {
  /** @deprecated use `ActivateRobotRequest$inboundSchema` instead. */
  export const inboundSchema = ActivateRobotRequest$inboundSchema;
  /** @deprecated use `ActivateRobotRequest$outboundSchema` instead. */
  export const outboundSchema = ActivateRobotRequest$outboundSchema;
  /** @deprecated use `ActivateRobotRequest$Outbound` instead. */
  export type Outbound = ActivateRobotRequest$Outbound;
}
