/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type GetRobotRequest = {
  /**
   * Unique identifier of the robot. This ID is generated upon robot creation and is required for subsequent operations on the robot.
   *
   * @remarks
   */
  robotId: string;
};

/** @internal */
export const GetRobotRequest$inboundSchema: z.ZodType<
  GetRobotRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  robotId: z.string(),
});

/** @internal */
export type GetRobotRequest$Outbound = {
  robotId: string;
};

/** @internal */
export const GetRobotRequest$outboundSchema: z.ZodType<
  GetRobotRequest$Outbound,
  z.ZodTypeDef,
  GetRobotRequest
> = z.object({
  robotId: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetRobotRequest$ {
  /** @deprecated use `GetRobotRequest$inboundSchema` instead. */
  export const inboundSchema = GetRobotRequest$inboundSchema;
  /** @deprecated use `GetRobotRequest$outboundSchema` instead. */
  export const outboundSchema = GetRobotRequest$outboundSchema;
  /** @deprecated use `GetRobotRequest$Outbound` instead. */
  export type Outbound = GetRobotRequest$Outbound;
}
