/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import * as components from "../components/index.js";

export type ListRobotsRequest = {
  /**
   * Page number of the results to retrieve.
   */
  page?: number | undefined;
  /**
   * Number of items per page.
   */
  pageSize?: number | undefined;
};

export type ListRobotsResponse = {
  result: components.RobotList;
};

/** @internal */
export const ListRobotsRequest$inboundSchema: z.ZodType<
  ListRobotsRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  page: z.number().int().default(1),
  pageSize: z.number().int().default(20),
});

/** @internal */
export type ListRobotsRequest$Outbound = {
  page: number;
  pageSize: number;
};

/** @internal */
export const ListRobotsRequest$outboundSchema: z.ZodType<
  ListRobotsRequest$Outbound,
  z.ZodTypeDef,
  ListRobotsRequest
> = z.object({
  page: z.number().int().default(1),
  pageSize: z.number().int().default(20),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ListRobotsRequest$ {
  /** @deprecated use `ListRobotsRequest$inboundSchema` instead. */
  export const inboundSchema = ListRobotsRequest$inboundSchema;
  /** @deprecated use `ListRobotsRequest$outboundSchema` instead. */
  export const outboundSchema = ListRobotsRequest$outboundSchema;
  /** @deprecated use `ListRobotsRequest$Outbound` instead. */
  export type Outbound = ListRobotsRequest$Outbound;
}

/** @internal */
export const ListRobotsResponse$inboundSchema: z.ZodType<
  ListRobotsResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  Result: components.RobotList$inboundSchema,
}).transform((v) => {
  return remap$(v, {
    "Result": "result",
  });
});

/** @internal */
export type ListRobotsResponse$Outbound = {
  Result: components.RobotList$Outbound;
};

/** @internal */
export const ListRobotsResponse$outboundSchema: z.ZodType<
  ListRobotsResponse$Outbound,
  z.ZodTypeDef,
  ListRobotsResponse
> = z.object({
  result: components.RobotList$outboundSchema,
}).transform((v) => {
  return remap$(v, {
    result: "Result",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ListRobotsResponse$ {
  /** @deprecated use `ListRobotsResponse$inboundSchema` instead. */
  export const inboundSchema = ListRobotsResponse$inboundSchema;
  /** @deprecated use `ListRobotsResponse$outboundSchema` instead. */
  export const outboundSchema = ListRobotsResponse$outboundSchema;
  /** @deprecated use `ListRobotsResponse$Outbound` instead. */
  export type Outbound = ListRobotsResponse$Outbound;
}
